<?php

$PUSHOVER_APP_TOKEN = 'PUSHOVER_APP_TOKEN';
$PUSHOVER_USER_KEY = 'USER_KEY';

$MYSQLI_HOST = 'HOST';
$MYSQLI_USERNAME = 'USERNAME';
$MYSQLI_PASSWORD = 'PASSWORD';
$MYSQLI_DATABASE = 'DATABASE';

?>